language: python
python:
  - "3.7.7"
  - "3.8"
dist: xenial

before_install:
  - git clone https://github.com/TravisToolbox/pycodestyle-travis.git

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install -e .

script:
    - black --skip-string-normalization --line-length 79 --diff --check ./multisim/
    - flake8
    - pytest --import-mode=importlib
    # - mypy

# after_success:
#   # Upload coverage data to codecov
#   - codecov
